name: Generate
on:
  push:
    branches:
      - raw

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: merge custom.txt
      run: |
        curl https://raw.githubusercontent.com/evilinsipid/gfwlist/master/gfwlist.txt > gfwlist.txt
        base64 -i -d gfwlist.txt > gfwlist_raw.txt
        sed -i '$d' gfwlist_raw.txt
        cat custom.txt >> gfwlist_raw.txt
        sed -i '/! Checksum:/d' gfwlist_raw.txt
        sed -i 's/! Expires: 6h/! Expires: 72h/' gfwlist_raw.txt
        nowtime=$(date "+%Y-%m-%d %H:%M:%S")
        sed -i "s/! Last Modified: Mon, 04 Nov 2019 11:21:47 -0500/! Last Modified: $nowtime/" gfwlist_raw.txt
        cat gfwlist_raw.txt | head -n 40
        cat gfwlist_raw.txt | tail -n 30
        base64 -i gfwlist_raw.txt > gfwlist.txt
        mkdir PushDir
        cp gfwlist.txt PushDir/
        cp gfwlist_raw.txt PushDir/
        
    - name: Commit files
      run: |
        cd ./PushDir
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "deployed by GitHub Action"
        
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'file'
        force: true
        directory: 'PushDir'
